meshConfig:
  enablePrometheusMerge: true
  accessLogFile: /dev/stdout
  accessLogEncoding: JSON
  accessLogFormat: |
    {
      "start_time": "%START_TIME%",
      "method": "%REQ(:METHOD)%",
      "path": "%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%",
      "protocol": "%PROTOCOL%",
      "response_code": "%RESPONSE_CODE%",
      "duration": "%DURATION%",
      "bytes_received": "%BYTES_RECEIVED%",
      "bytes_sent": "%BYTES_SENT%",
      "upstream_host": "%UPSTREAM_HOST%",
      "downstream_remote_address": "%DOWNSTREAM_REMOTE_ADDRESS%",
      "user_agent": "%REQ(USER-AGENT)%",
      "request_id": "%REQ(X-REQUEST-ID)%",
      "x_forwarded_for": "%REQ(X-FORWARDED-FOR)%"
      "authority": "%REQ(:AUTHORITY)%"
    }
