apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: my-app-cert
  namespace: default
spec:
  secretName: my-app-tls
  commonName: my-app.local
  dnsNames:
    - my-app.local
  issuerRef:
    name: my-ca-issuer
    kind: ClusterIssuer

